# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Validate development container

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_images:
    name: Build development image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - name: Build development image
            target_step: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup docker context for buildx
        run: |
          docker context create builders || docker context use builders

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v4.3.0

      - name: ${{ matrix.target.name }}
        uses: docker/build-push-action@v7.3.0
        with:
          push: false
          context: .
          file: ./docker/Dockerfile
          target: ${{ matrix.target.target_step }}
          tags: coc-ai-controller-dev:ci
          sbom: false
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
